version: "3.8"

services:
  ai_radio_backend:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
